const files =[
    {
        "companyCode": "01",
        "deptName": "印刷组",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "21",
        "orderNum": "10",
        "label": "印刷组",
        "delFlag": "0",
        "parentId": "19",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:40:41",
        "id": "21",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "上光组",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "20",
        "orderNum": "10",
        "label": "上光组",
        "delFlag": "0",
        "parentId": "19",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:40:22",
        "id": "20",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "印刷部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "19",
        "orderNum": "10",
        "label": "印刷部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:40:01",
        "id": "19",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "物流组",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "18",
        "orderNum": "10",
        "label": "物流组",
        "delFlag": "0",
        "parentId": "12",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:38:39",
        "id": "18",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "物流组",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "17",
        "orderNum": "10",
        "label": "物流组",
        "delFlag": "2",
        "parentId": "11",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:38:24",
        "id": "17",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "成品仓",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "16",
        "orderNum": "10",
        "label": "成品仓",
        "delFlag": "0",
        "parentId": "12",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:38:09",
        "id": "16",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "货仓组",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "15",
        "orderNum": "10",
        "label": "货仓组",
        "delFlag": "0",
        "parentId": "12",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-18 19:37:47",
        "id": "15",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "行政部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "14",
        "orderNum": "10",
        "label": "行政部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:20:28",
        "id": "14",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "成本部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "13",
        "orderNum": "10",
        "label": "成本部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:20:15",
        "id": "13",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "仓储物流部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "12",
        "orderNum": "10",
        "label": "仓储物流部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:19:08",
        "id": "12",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "生产部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "11",
        "orderNum": "10",
        "label": "生产部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:18:49",
        "id": "11",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "计划部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "10",
        "orderNum": "10",
        "label": "计划部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:18:18",
        "id": "10",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "工程技术部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "9",
        "orderNum": "10",
        "label": "工程技术部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:17:55",
        "id": "9",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "集团营销部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "8",
        "orderNum": "10",
        "label": "集团营销部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:17:38",
        "id": "8",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "总经办",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "7",
        "orderNum": "10",
        "updateTime": "2024-12-12 11:17:13",
        "label": "总经办",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "admin",
        "createTime": "2024-12-12 11:15:19",
        "id": "7",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "IT部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "6",
        "orderNum": "10",
        "label": "IT部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:14:39",
        "id": "6",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "财务部",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "5",
        "orderNum": "10",
        "label": "财务部",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:14:24",
        "id": "5",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "董事会办公室",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "4",
        "orderNum": "10",
        "label": "董事会办公室",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:13:56",
        "id": "4",
        "ancestors": "0,1,2",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "董事会",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "3",
        "orderNum": "10",
        "label": "董事会",
        "delFlag": "0",
        "parentId": "2",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:13:29",
        "id": "3",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "广东彩乐",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "2",
        "orderNum": "10",
        "label": "广东彩乐",
        "delFlag": "0",
        "parentId": "1",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "",
        "createTime": "2024-12-12 11:10:45",
        "id": "2",
        "status": "1"
    },
    {
        "companyCode": "01",
        "deptName": "彩乐集团",
        "companyName": "广东彩乐智能包装科技有限公司",
        "deptId": "1",
        "orderNum": "10",
        "updateTime": "2024-12-12 11:09:33",
        "label": "彩乐集团",
        "delFlag": "0",
        "parentId": "0",
        "companySname": "广东彩乐",
        "createBy": "admin",
        "companyId": "1867038441179582464",
        "updateBy": "admin",
        "id": "1",
        "status": "1"
    }
]
export function getData() {
    return files;
}